// Code generated by go-swagger; DO NOT EDIT.

package backups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/yugabyte/yb-tools/yugaware-client/pkg/client/swagger/models"
)

// DeleteBackupsv2Reader is a Reader for the DeleteBackupsv2 structure.
type DeleteBackupsv2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteBackupsv2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteBackupsv2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteBackupsv2OK creates a DeleteBackupsv2OK with default headers values
func NewDeleteBackupsv2OK() *DeleteBackupsv2OK {
	return &DeleteBackupsv2OK{}
}

/*
	DeleteBackupsv2OK describes a response with status code 200, with default header values.

successful operation
*/
type DeleteBackupsv2OK struct {
	Payload models.YBPTasks
}

func (o *DeleteBackupsv2OK) Error() string {
	return fmt.Sprintf("[POST /api/v1/customers/{cUUID}/backups/delete][%d] deleteBackupsv2OK  %+v", 200, o.Payload)
}
func (o *DeleteBackupsv2OK) GetPayload() models.YBPTasks {
	return o.Payload
}

func (o *DeleteBackupsv2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
