// Code generated by go-swagger; DO NOT EDIT.

package universe_upgrades_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/yugabyte/yb-tools/yugaware-client/pkg/client/swagger/models"
)

// NewUpgradeSoftwareParams creates a new UpgradeSoftwareParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpgradeSoftwareParams() *UpgradeSoftwareParams {
	return &UpgradeSoftwareParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpgradeSoftwareParamsWithTimeout creates a new UpgradeSoftwareParams object
// with the ability to set a timeout on a request.
func NewUpgradeSoftwareParamsWithTimeout(timeout time.Duration) *UpgradeSoftwareParams {
	return &UpgradeSoftwareParams{
		timeout: timeout,
	}
}

// NewUpgradeSoftwareParamsWithContext creates a new UpgradeSoftwareParams object
// with the ability to set a context for a request.
func NewUpgradeSoftwareParamsWithContext(ctx context.Context) *UpgradeSoftwareParams {
	return &UpgradeSoftwareParams{
		Context: ctx,
	}
}

// NewUpgradeSoftwareParamsWithHTTPClient creates a new UpgradeSoftwareParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpgradeSoftwareParamsWithHTTPClient(client *http.Client) *UpgradeSoftwareParams {
	return &UpgradeSoftwareParams{
		HTTPClient: client,
	}
}

/* UpgradeSoftwareParams contains all the parameters to send to the API endpoint
   for the upgrade software operation.

   Typically these are written to a http.Request.
*/
type UpgradeSoftwareParams struct {

	// CUUID.
	//
	// Format: uuid
	CUUID strfmt.UUID

	/* SoftwareUpgradeParams.

	   Software Upgrade Params
	*/
	SoftwareUpgradeParams *models.SoftwareUpgradeParams

	// UniUUID.
	//
	// Format: uuid
	UniUUID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the upgrade software params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpgradeSoftwareParams) WithDefaults() *UpgradeSoftwareParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the upgrade software params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpgradeSoftwareParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the upgrade software params
func (o *UpgradeSoftwareParams) WithTimeout(timeout time.Duration) *UpgradeSoftwareParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the upgrade software params
func (o *UpgradeSoftwareParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the upgrade software params
func (o *UpgradeSoftwareParams) WithContext(ctx context.Context) *UpgradeSoftwareParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the upgrade software params
func (o *UpgradeSoftwareParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the upgrade software params
func (o *UpgradeSoftwareParams) WithHTTPClient(client *http.Client) *UpgradeSoftwareParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the upgrade software params
func (o *UpgradeSoftwareParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCUUID adds the cUUID to the upgrade software params
func (o *UpgradeSoftwareParams) WithCUUID(cUUID strfmt.UUID) *UpgradeSoftwareParams {
	o.SetCUUID(cUUID)
	return o
}

// SetCUUID adds the cUuid to the upgrade software params
func (o *UpgradeSoftwareParams) SetCUUID(cUUID strfmt.UUID) {
	o.CUUID = cUUID
}

// WithSoftwareUpgradeParams adds the softwareUpgradeParams to the upgrade software params
func (o *UpgradeSoftwareParams) WithSoftwareUpgradeParams(softwareUpgradeParams *models.SoftwareUpgradeParams) *UpgradeSoftwareParams {
	o.SetSoftwareUpgradeParams(softwareUpgradeParams)
	return o
}

// SetSoftwareUpgradeParams adds the softwareUpgradeParams to the upgrade software params
func (o *UpgradeSoftwareParams) SetSoftwareUpgradeParams(softwareUpgradeParams *models.SoftwareUpgradeParams) {
	o.SoftwareUpgradeParams = softwareUpgradeParams
}

// WithUniUUID adds the uniUUID to the upgrade software params
func (o *UpgradeSoftwareParams) WithUniUUID(uniUUID strfmt.UUID) *UpgradeSoftwareParams {
	o.SetUniUUID(uniUUID)
	return o
}

// SetUniUUID adds the uniUuid to the upgrade software params
func (o *UpgradeSoftwareParams) SetUniUUID(uniUUID strfmt.UUID) {
	o.UniUUID = uniUUID
}

// WriteToRequest writes these params to a swagger request
func (o *UpgradeSoftwareParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cUUID
	if err := r.SetPathParam("cUUID", o.CUUID.String()); err != nil {
		return err
	}
	if o.SoftwareUpgradeParams != nil {
		if err := r.SetBodyParam(o.SoftwareUpgradeParams); err != nil {
			return err
		}
	}

	// path param uniUUID
	if err := r.SetPathParam("uniUUID", o.UniUUID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
