// Code generated by go-swagger; DO NOT EDIT.

package asynchronous_replication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetXClusterConfigParams creates a new GetXClusterConfigParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetXClusterConfigParams() *GetXClusterConfigParams {
	return &GetXClusterConfigParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetXClusterConfigParamsWithTimeout creates a new GetXClusterConfigParams object
// with the ability to set a timeout on a request.
func NewGetXClusterConfigParamsWithTimeout(timeout time.Duration) *GetXClusterConfigParams {
	return &GetXClusterConfigParams{
		timeout: timeout,
	}
}

// NewGetXClusterConfigParamsWithContext creates a new GetXClusterConfigParams object
// with the ability to set a context for a request.
func NewGetXClusterConfigParamsWithContext(ctx context.Context) *GetXClusterConfigParams {
	return &GetXClusterConfigParams{
		Context: ctx,
	}
}

// NewGetXClusterConfigParamsWithHTTPClient creates a new GetXClusterConfigParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetXClusterConfigParamsWithHTTPClient(client *http.Client) *GetXClusterConfigParams {
	return &GetXClusterConfigParams{
		HTTPClient: client,
	}
}

/* GetXClusterConfigParams contains all the parameters to send to the API endpoint
   for the get x cluster config operation.

   Typically these are written to a http.Request.
*/
type GetXClusterConfigParams struct {

	// CUUID.
	//
	// Format: uuid
	CUUID strfmt.UUID

	// XccUUID.
	//
	// Format: uuid
	XccUUID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get x cluster config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetXClusterConfigParams) WithDefaults() *GetXClusterConfigParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get x cluster config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetXClusterConfigParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get x cluster config params
func (o *GetXClusterConfigParams) WithTimeout(timeout time.Duration) *GetXClusterConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get x cluster config params
func (o *GetXClusterConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get x cluster config params
func (o *GetXClusterConfigParams) WithContext(ctx context.Context) *GetXClusterConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get x cluster config params
func (o *GetXClusterConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get x cluster config params
func (o *GetXClusterConfigParams) WithHTTPClient(client *http.Client) *GetXClusterConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get x cluster config params
func (o *GetXClusterConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCUUID adds the cUUID to the get x cluster config params
func (o *GetXClusterConfigParams) WithCUUID(cUUID strfmt.UUID) *GetXClusterConfigParams {
	o.SetCUUID(cUUID)
	return o
}

// SetCUUID adds the cUuid to the get x cluster config params
func (o *GetXClusterConfigParams) SetCUUID(cUUID strfmt.UUID) {
	o.CUUID = cUUID
}

// WithXccUUID adds the xccUUID to the get x cluster config params
func (o *GetXClusterConfigParams) WithXccUUID(xccUUID strfmt.UUID) *GetXClusterConfigParams {
	o.SetXccUUID(xccUUID)
	return o
}

// SetXccUUID adds the xccUuid to the get x cluster config params
func (o *GetXClusterConfigParams) SetXccUUID(xccUUID strfmt.UUID) {
	o.XccUUID = xccUUID
}

// WriteToRequest writes these params to a swagger request
func (o *GetXClusterConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cUUID
	if err := r.SetPathParam("cUUID", o.CUUID.String()); err != nil {
		return err
	}

	// path param xccUUID
	if err := r.SetPathParam("xccUUID", o.XccUUID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
