// Code generated by go-swagger; DO NOT EDIT.

package logging_config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/yugabyte/yb-tools/yugaware-client/pkg/client/swagger/models"
)

// NewSetAuditLoggingSettingsParams creates a new SetAuditLoggingSettingsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSetAuditLoggingSettingsParams() *SetAuditLoggingSettingsParams {
	return &SetAuditLoggingSettingsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSetAuditLoggingSettingsParamsWithTimeout creates a new SetAuditLoggingSettingsParams object
// with the ability to set a timeout on a request.
func NewSetAuditLoggingSettingsParamsWithTimeout(timeout time.Duration) *SetAuditLoggingSettingsParams {
	return &SetAuditLoggingSettingsParams{
		timeout: timeout,
	}
}

// NewSetAuditLoggingSettingsParamsWithContext creates a new SetAuditLoggingSettingsParams object
// with the ability to set a context for a request.
func NewSetAuditLoggingSettingsParamsWithContext(ctx context.Context) *SetAuditLoggingSettingsParams {
	return &SetAuditLoggingSettingsParams{
		Context: ctx,
	}
}

// NewSetAuditLoggingSettingsParamsWithHTTPClient creates a new SetAuditLoggingSettingsParams object
// with the ability to set a custom HTTPClient for a request.
func NewSetAuditLoggingSettingsParamsWithHTTPClient(client *http.Client) *SetAuditLoggingSettingsParams {
	return &SetAuditLoggingSettingsParams{
		HTTPClient: client,
	}
}

/*
SetAuditLoggingSettingsParams contains all the parameters to send to the API endpoint

	for the set audit logging settings operation.

	Typically these are written to a http.Request.
*/
type SetAuditLoggingSettingsParams struct {

	/* AuditLoggingConfig.

	   Audit Logging config to be updated
	*/
	AuditLoggingConfig *models.AuditLoggingConfig

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the set audit logging settings params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetAuditLoggingSettingsParams) WithDefaults() *SetAuditLoggingSettingsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the set audit logging settings params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetAuditLoggingSettingsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the set audit logging settings params
func (o *SetAuditLoggingSettingsParams) WithTimeout(timeout time.Duration) *SetAuditLoggingSettingsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set audit logging settings params
func (o *SetAuditLoggingSettingsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set audit logging settings params
func (o *SetAuditLoggingSettingsParams) WithContext(ctx context.Context) *SetAuditLoggingSettingsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set audit logging settings params
func (o *SetAuditLoggingSettingsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set audit logging settings params
func (o *SetAuditLoggingSettingsParams) WithHTTPClient(client *http.Client) *SetAuditLoggingSettingsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set audit logging settings params
func (o *SetAuditLoggingSettingsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuditLoggingConfig adds the auditLoggingConfig to the set audit logging settings params
func (o *SetAuditLoggingSettingsParams) WithAuditLoggingConfig(auditLoggingConfig *models.AuditLoggingConfig) *SetAuditLoggingSettingsParams {
	o.SetAuditLoggingConfig(auditLoggingConfig)
	return o
}

// SetAuditLoggingConfig adds the auditLoggingConfig to the set audit logging settings params
func (o *SetAuditLoggingSettingsParams) SetAuditLoggingConfig(auditLoggingConfig *models.AuditLoggingConfig) {
	o.AuditLoggingConfig = auditLoggingConfig
}

// WriteToRequest writes these params to a swagger request
func (o *SetAuditLoggingSettingsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.AuditLoggingConfig != nil {
		if err := r.SetBodyParam(o.AuditLoggingConfig); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
