// Code generated by go-swagger; DO NOT EDIT.

package universe_node_metadata_metamaster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/yugabyte/yb-tools/yugaware-client/pkg/client/swagger/models"
)

// GetUniverseMasterNodesReader is a Reader for the GetUniverseMasterNodes structure.
type GetUniverseMasterNodesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUniverseMasterNodesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetUniverseMasterNodesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetUniverseMasterNodesOK creates a GetUniverseMasterNodesOK with default headers values
func NewGetUniverseMasterNodesOK() *GetUniverseMasterNodesOK {
	return &GetUniverseMasterNodesOK{}
}

/* GetUniverseMasterNodesOK describes a response with status code 200, with default header values.

successful operation
*/
type GetUniverseMasterNodesOK struct {
	Payload *models.MastersList
}

func (o *GetUniverseMasterNodesOK) Error() string {
	return fmt.Sprintf("[GET /metamaster/universe/{universeUUID}][%d] getUniverseMasterNodesOK  %+v", 200, o.Payload)
}
func (o *GetUniverseMasterNodesOK) GetPayload() *models.MastersList {
	return o.Payload
}

func (o *GetUniverseMasterNodesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MastersList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
