// Code generated by go-swagger; DO NOT EDIT.

package node_instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/yugabyte/yb-tools/yugaware-client/pkg/client/swagger/models"
)

// NewCreateNodeInstanceParams creates a new CreateNodeInstanceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateNodeInstanceParams() *CreateNodeInstanceParams {
	return &CreateNodeInstanceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateNodeInstanceParamsWithTimeout creates a new CreateNodeInstanceParams object
// with the ability to set a timeout on a request.
func NewCreateNodeInstanceParamsWithTimeout(timeout time.Duration) *CreateNodeInstanceParams {
	return &CreateNodeInstanceParams{
		timeout: timeout,
	}
}

// NewCreateNodeInstanceParamsWithContext creates a new CreateNodeInstanceParams object
// with the ability to set a context for a request.
func NewCreateNodeInstanceParamsWithContext(ctx context.Context) *CreateNodeInstanceParams {
	return &CreateNodeInstanceParams{
		Context: ctx,
	}
}

// NewCreateNodeInstanceParamsWithHTTPClient creates a new CreateNodeInstanceParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateNodeInstanceParamsWithHTTPClient(client *http.Client) *CreateNodeInstanceParams {
	return &CreateNodeInstanceParams{
		HTTPClient: client,
	}
}

/* CreateNodeInstanceParams contains all the parameters to send to the API endpoint
   for the create node instance operation.

   Typically these are written to a http.Request.
*/
type CreateNodeInstanceParams struct {

	/* NodeInstance.

	   Node instance data to be created
	*/
	NodeInstance *models.NodeInstanceFormData

	// AzUUID.
	//
	// Format: uuid
	AzUUID strfmt.UUID

	// CUUID.
	//
	// Format: uuid
	CUUID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create node instance params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateNodeInstanceParams) WithDefaults() *CreateNodeInstanceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create node instance params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateNodeInstanceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create node instance params
func (o *CreateNodeInstanceParams) WithTimeout(timeout time.Duration) *CreateNodeInstanceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create node instance params
func (o *CreateNodeInstanceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create node instance params
func (o *CreateNodeInstanceParams) WithContext(ctx context.Context) *CreateNodeInstanceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create node instance params
func (o *CreateNodeInstanceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create node instance params
func (o *CreateNodeInstanceParams) WithHTTPClient(client *http.Client) *CreateNodeInstanceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create node instance params
func (o *CreateNodeInstanceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNodeInstance adds the nodeInstance to the create node instance params
func (o *CreateNodeInstanceParams) WithNodeInstance(nodeInstance *models.NodeInstanceFormData) *CreateNodeInstanceParams {
	o.SetNodeInstance(nodeInstance)
	return o
}

// SetNodeInstance adds the nodeInstance to the create node instance params
func (o *CreateNodeInstanceParams) SetNodeInstance(nodeInstance *models.NodeInstanceFormData) {
	o.NodeInstance = nodeInstance
}

// WithAzUUID adds the azUUID to the create node instance params
func (o *CreateNodeInstanceParams) WithAzUUID(azUUID strfmt.UUID) *CreateNodeInstanceParams {
	o.SetAzUUID(azUUID)
	return o
}

// SetAzUUID adds the azUuid to the create node instance params
func (o *CreateNodeInstanceParams) SetAzUUID(azUUID strfmt.UUID) {
	o.AzUUID = azUUID
}

// WithCUUID adds the cUUID to the create node instance params
func (o *CreateNodeInstanceParams) WithCUUID(cUUID strfmt.UUID) *CreateNodeInstanceParams {
	o.SetCUUID(cUUID)
	return o
}

// SetCUUID adds the cUuid to the create node instance params
func (o *CreateNodeInstanceParams) SetCUUID(cUUID strfmt.UUID) {
	o.CUUID = cUUID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateNodeInstanceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.NodeInstance != nil {
		if err := r.SetBodyParam(o.NodeInstance); err != nil {
			return err
		}
	}

	// path param azUUID
	if err := r.SetPathParam("azUUID", o.AzUUID.String()); err != nil {
		return err
	}

	// path param cUUID
	if err := r.SetPathParam("cUUID", o.CUUID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
