// Code generated by go-swagger; DO NOT EDIT.

package runtime_configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteKeyReader is a Reader for the DeleteKey structure.
type DeleteKeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteKeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewDeleteKeyDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewDeleteKeyDefault creates a DeleteKeyDefault with default headers values
func NewDeleteKeyDefault(code int) *DeleteKeyDefault {
	return &DeleteKeyDefault{
		_statusCode: code,
	}
}

/* DeleteKeyDefault describes a response with status code -1, with default header values.

successful operation
*/
type DeleteKeyDefault struct {
	_statusCode int
}

// Code gets the status code for the delete key default response
func (o *DeleteKeyDefault) Code() int {
	return o._statusCode
}

func (o *DeleteKeyDefault) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/customers/{cUUID}/runtime_config/{scope}/key/{key}][%d] deleteKey default ", o._statusCode)
}

func (o *DeleteKeyDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
