// Code generated by go-swagger; DO NOT EDIT.

package cloud_providers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/yugabyte/yb-tools/yugaware-client/pkg/client/swagger/models"
)

// NewEditProviderParams creates a new EditProviderParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEditProviderParams() *EditProviderParams {
	return &EditProviderParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewEditProviderParamsWithTimeout creates a new EditProviderParams object
// with the ability to set a timeout on a request.
func NewEditProviderParamsWithTimeout(timeout time.Duration) *EditProviderParams {
	return &EditProviderParams{
		timeout: timeout,
	}
}

// NewEditProviderParamsWithContext creates a new EditProviderParams object
// with the ability to set a context for a request.
func NewEditProviderParamsWithContext(ctx context.Context) *EditProviderParams {
	return &EditProviderParams{
		Context: ctx,
	}
}

// NewEditProviderParamsWithHTTPClient creates a new EditProviderParams object
// with the ability to set a custom HTTPClient for a request.
func NewEditProviderParamsWithHTTPClient(client *http.Client) *EditProviderParams {
	return &EditProviderParams{
		HTTPClient: client,
	}
}

/*
EditProviderParams contains all the parameters to send to the API endpoint

	for the edit provider operation.

	Typically these are written to a http.Request.
*/
type EditProviderParams struct {

	/* EditProviderRequest.

	   edit provider form data
	*/
	EditProviderRequest *models.Provider

	// CUUID.
	//
	// Format: uuid
	CUUID strfmt.UUID

	// PUUID.
	//
	// Format: uuid
	PUUID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the edit provider params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EditProviderParams) WithDefaults() *EditProviderParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the edit provider params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EditProviderParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the edit provider params
func (o *EditProviderParams) WithTimeout(timeout time.Duration) *EditProviderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the edit provider params
func (o *EditProviderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the edit provider params
func (o *EditProviderParams) WithContext(ctx context.Context) *EditProviderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the edit provider params
func (o *EditProviderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the edit provider params
func (o *EditProviderParams) WithHTTPClient(client *http.Client) *EditProviderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the edit provider params
func (o *EditProviderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEditProviderRequest adds the editProviderRequest to the edit provider params
func (o *EditProviderParams) WithEditProviderRequest(editProviderRequest *models.Provider) *EditProviderParams {
	o.SetEditProviderRequest(editProviderRequest)
	return o
}

// SetEditProviderRequest adds the editProviderRequest to the edit provider params
func (o *EditProviderParams) SetEditProviderRequest(editProviderRequest *models.Provider) {
	o.EditProviderRequest = editProviderRequest
}

// WithCUUID adds the cUUID to the edit provider params
func (o *EditProviderParams) WithCUUID(cUUID strfmt.UUID) *EditProviderParams {
	o.SetCUUID(cUUID)
	return o
}

// SetCUUID adds the cUuid to the edit provider params
func (o *EditProviderParams) SetCUUID(cUUID strfmt.UUID) {
	o.CUUID = cUUID
}

// WithPUUID adds the pUUID to the edit provider params
func (o *EditProviderParams) WithPUUID(pUUID strfmt.UUID) *EditProviderParams {
	o.SetPUUID(pUUID)
	return o
}

// SetPUUID adds the pUuid to the edit provider params
func (o *EditProviderParams) SetPUUID(pUUID strfmt.UUID) {
	o.PUUID = pUUID
}

// WriteToRequest writes these params to a swagger request
func (o *EditProviderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.EditProviderRequest != nil {
		if err := r.SetBodyParam(o.EditProviderRequest); err != nil {
			return err
		}
	}

	// path param cUUID
	if err := r.SetPathParam("cUUID", o.CUUID.String()); err != nil {
		return err
	}

	// path param pUUID
	if err := r.SetPathParam("pUUID", o.PUUID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
