// Code generated by go-swagger; DO NOT EDIT.

package universe_database_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreateUserInDBParams creates a new CreateUserInDBParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateUserInDBParams() *CreateUserInDBParams {
	return &CreateUserInDBParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateUserInDBParamsWithTimeout creates a new CreateUserInDBParams object
// with the ability to set a timeout on a request.
func NewCreateUserInDBParamsWithTimeout(timeout time.Duration) *CreateUserInDBParams {
	return &CreateUserInDBParams{
		timeout: timeout,
	}
}

// NewCreateUserInDBParamsWithContext creates a new CreateUserInDBParams object
// with the ability to set a context for a request.
func NewCreateUserInDBParamsWithContext(ctx context.Context) *CreateUserInDBParams {
	return &CreateUserInDBParams{
		Context: ctx,
	}
}

// NewCreateUserInDBParamsWithHTTPClient creates a new CreateUserInDBParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateUserInDBParamsWithHTTPClient(client *http.Client) *CreateUserInDBParams {
	return &CreateUserInDBParams{
		HTTPClient: client,
	}
}

/*
CreateUserInDBParams contains all the parameters to send to the API endpoint

	for the create user in d b operation.

	Typically these are written to a http.Request.
*/
type CreateUserInDBParams struct {

	// CUUID.
	//
	// Format: uuid
	CUUID strfmt.UUID

	// UniUUID.
	//
	// Format: uuid
	UniUUID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create user in d b params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateUserInDBParams) WithDefaults() *CreateUserInDBParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create user in d b params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateUserInDBParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create user in d b params
func (o *CreateUserInDBParams) WithTimeout(timeout time.Duration) *CreateUserInDBParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create user in d b params
func (o *CreateUserInDBParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create user in d b params
func (o *CreateUserInDBParams) WithContext(ctx context.Context) *CreateUserInDBParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create user in d b params
func (o *CreateUserInDBParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create user in d b params
func (o *CreateUserInDBParams) WithHTTPClient(client *http.Client) *CreateUserInDBParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create user in d b params
func (o *CreateUserInDBParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCUUID adds the cUUID to the create user in d b params
func (o *CreateUserInDBParams) WithCUUID(cUUID strfmt.UUID) *CreateUserInDBParams {
	o.SetCUUID(cUUID)
	return o
}

// SetCUUID adds the cUuid to the create user in d b params
func (o *CreateUserInDBParams) SetCUUID(cUUID strfmt.UUID) {
	o.CUUID = cUUID
}

// WithUniUUID adds the uniUUID to the create user in d b params
func (o *CreateUserInDBParams) WithUniUUID(uniUUID strfmt.UUID) *CreateUserInDBParams {
	o.SetUniUUID(uniUUID)
	return o
}

// SetUniUUID adds the uniUuid to the create user in d b params
func (o *CreateUserInDBParams) SetUniUUID(uniUUID strfmt.UUID) {
	o.UniUUID = uniUUID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateUserInDBParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cUUID
	if err := r.SetPathParam("cUUID", o.CUUID.String()); err != nil {
		return err
	}

	// path param uniUUID
	if err := r.SetPathParam("uniUUID", o.UniUUID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
