// Code generated by go-swagger; DO NOT EDIT.

package schedule_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/yugabyte/yb-tools/yugaware-client/pkg/client/swagger/models"
)

// NewListSchedulesV2Params creates a new ListSchedulesV2Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListSchedulesV2Params() *ListSchedulesV2Params {
	return &ListSchedulesV2Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewListSchedulesV2ParamsWithTimeout creates a new ListSchedulesV2Params object
// with the ability to set a timeout on a request.
func NewListSchedulesV2ParamsWithTimeout(timeout time.Duration) *ListSchedulesV2Params {
	return &ListSchedulesV2Params{
		timeout: timeout,
	}
}

// NewListSchedulesV2ParamsWithContext creates a new ListSchedulesV2Params object
// with the ability to set a context for a request.
func NewListSchedulesV2ParamsWithContext(ctx context.Context) *ListSchedulesV2Params {
	return &ListSchedulesV2Params{
		Context: ctx,
	}
}

// NewListSchedulesV2ParamsWithHTTPClient creates a new ListSchedulesV2Params object
// with the ability to set a custom HTTPClient for a request.
func NewListSchedulesV2ParamsWithHTTPClient(client *http.Client) *ListSchedulesV2Params {
	return &ListSchedulesV2Params{
		HTTPClient: client,
	}
}

/*
ListSchedulesV2Params contains all the parameters to send to the API endpoint

	for the list schedules v2 operation.

	Typically these are written to a http.Request.
*/
type ListSchedulesV2Params struct {

	// PageScheduleRequest.
	PageScheduleRequest *models.SchedulePagedAPIQuery

	// CUUID.
	//
	// Format: uuid
	CUUID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list schedules v2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListSchedulesV2Params) WithDefaults() *ListSchedulesV2Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list schedules v2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListSchedulesV2Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list schedules v2 params
func (o *ListSchedulesV2Params) WithTimeout(timeout time.Duration) *ListSchedulesV2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list schedules v2 params
func (o *ListSchedulesV2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list schedules v2 params
func (o *ListSchedulesV2Params) WithContext(ctx context.Context) *ListSchedulesV2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list schedules v2 params
func (o *ListSchedulesV2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list schedules v2 params
func (o *ListSchedulesV2Params) WithHTTPClient(client *http.Client) *ListSchedulesV2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list schedules v2 params
func (o *ListSchedulesV2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPageScheduleRequest adds the pageScheduleRequest to the list schedules v2 params
func (o *ListSchedulesV2Params) WithPageScheduleRequest(pageScheduleRequest *models.SchedulePagedAPIQuery) *ListSchedulesV2Params {
	o.SetPageScheduleRequest(pageScheduleRequest)
	return o
}

// SetPageScheduleRequest adds the pageScheduleRequest to the list schedules v2 params
func (o *ListSchedulesV2Params) SetPageScheduleRequest(pageScheduleRequest *models.SchedulePagedAPIQuery) {
	o.PageScheduleRequest = pageScheduleRequest
}

// WithCUUID adds the cUUID to the list schedules v2 params
func (o *ListSchedulesV2Params) WithCUUID(cUUID strfmt.UUID) *ListSchedulesV2Params {
	o.SetCUUID(cUUID)
	return o
}

// SetCUUID adds the cUuid to the list schedules v2 params
func (o *ListSchedulesV2Params) SetCUUID(cUUID strfmt.UUID) {
	o.CUUID = cUUID
}

// WriteToRequest writes these params to a swagger request
func (o *ListSchedulesV2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.PageScheduleRequest != nil {
		if err := r.SetBodyParam(o.PageScheduleRequest); err != nil {
			return err
		}
	}

	// path param cUUID
	if err := r.SetPathParam("cUUID", o.CUUID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
