// Code generated by go-swagger; DO NOT EDIT.

package support_bundle_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DownloadSupportBundleReader is a Reader for the DownloadSupportBundle structure.
type DownloadSupportBundleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DownloadSupportBundleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDownloadSupportBundleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDownloadSupportBundleOK creates a DownloadSupportBundleOK with default headers values
func NewDownloadSupportBundleOK() *DownloadSupportBundleOK {
	return &DownloadSupportBundleOK{}
}

/*
	DownloadSupportBundleOK describes a response with status code 200, with default header values.

successful operation
*/
type DownloadSupportBundleOK struct {
	Payload string
}

func (o *DownloadSupportBundleOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/customers/{cUUID}/universes/{uniUUID}/support_bundle/{sbUUID}/download][%d] downloadSupportBundleOK  %+v", 200, o.Payload)
}
func (o *DownloadSupportBundleOK) GetPayload() string {
	return o.Payload
}

func (o *DownloadSupportBundleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
