// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PackagePaths package paths
//
// swagger:model PackagePaths
type PackagePaths struct {

	// Path to x86_64 package
	X8664 string `json:"x86_64,omitempty"`

	// Checksum for x86_64 package
	X8664Checksum string `json:"x86_64_checksum,omitempty"`
}

// Validate validates this package paths
func (m *PackagePaths) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this package paths based on context it is used
func (m *PackagePaths) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PackagePaths) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PackagePaths) UnmarshalBinary(b []byte) error {
	var res PackagePaths
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
