// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PlacementBlock placement block
//
// swagger:model PlacementBlock
type PlacementBlock struct {

	// Cloud
	Cloud string `json:"cloud,omitempty"`

	// Minimum replicas
	MinNumReplicas int32 `json:"minNumReplicas,omitempty"`

	// Region
	Region string `json:"region,omitempty"`

	// Zone
	Zone string `json:"zone,omitempty"`
}

// Validate validates this placement block
func (m *PlacementBlock) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this placement block based on context it is used
func (m *PlacementBlock) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PlacementBlock) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PlacementBlock) UnmarshalBinary(b []byte) error {
	var res PlacementBlock
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
