// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
//
// The following only applies to changes made to this file as part of YugaByte development.
//
// Portions Copyright (c) YugaByte, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.  You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License
// is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
// or implied.  See the License for the specific language governing permissions and limitations
// under the License.
//

// Code generated by protoc-gen-ybrpc. DO NOT EDIT.

package consensus

import (
	"github.com/go-logr/logr"
	"github.com/yugabyte/yb-tools/protoc-gen-ybrpc/pkg/message"
)

// service: yb.consensus.ConsensusService
// service: ConsensusService
// A Raft implementation.

type ConsensusService interface {
	UpdateConsensus(request *ConsensusRequestPB) (*ConsensusResponsePB, error)
	RequestConsensusVote(request *VoteRequestPB) (*VoteResponsePB, error)
	ChangeConfig(request *ChangeConfigRequestPB) (*ChangeConfigResponsePB, error)
	GetNodeInstance(request *GetNodeInstanceRequestPB) (*GetNodeInstanceResponsePB, error)
	RunLeaderElection(request *RunLeaderElectionRequestPB) (*RunLeaderElectionResponsePB, error)
	LeaderElectionLost(request *LeaderElectionLostRequestPB) (*LeaderElectionLostResponsePB, error)
	LeaderStepDown(request *LeaderStepDownRequestPB) (*LeaderStepDownResponsePB, error)
	GetLastOpId(request *GetLastOpIdRequestPB) (*GetLastOpIdResponsePB, error)
	GetConsensusState(request *GetConsensusStateRequestPB) (*GetConsensusStateResponsePB, error)
	StartRemoteBootstrap(request *StartRemoteBootstrapRequestPB) (*StartRemoteBootstrapResponsePB, error)
}

type ConsensusServiceImpl struct {
	Log       logr.Logger
	Messenger message.Messenger
}

// Analogous to AppendEntries in Raft, but only used for followers.

func (s *ConsensusServiceImpl) UpdateConsensus(request *ConsensusRequestPB) (*ConsensusResponsePB, error) {
	s.Log.V(1).Info("sending RPC message", "service", "yb.consensus.ConsensusService", "method", "UpdateConsensus", "message", request)
	response := &ConsensusResponsePB{}

	err := s.Messenger.SendMessage("yb.consensus.ConsensusService", "UpdateConsensus", request.ProtoReflect().Interface(), response.ProtoReflect().Interface())
	if err != nil {
		return nil, err
	}

	s.Log.V(1).Info("received RPC response", "service", "yb.consensus.ConsensusService", "method", "UpdateConsensus", "message", response)

	return response, nil
}

// RequestVote() from Raft.

func (s *ConsensusServiceImpl) RequestConsensusVote(request *VoteRequestPB) (*VoteResponsePB, error) {
	s.Log.V(1).Info("sending RPC message", "service", "yb.consensus.ConsensusService", "method", "RequestConsensusVote", "message", request)
	response := &VoteResponsePB{}

	err := s.Messenger.SendMessage("yb.consensus.ConsensusService", "RequestConsensusVote", request.ProtoReflect().Interface(), response.ProtoReflect().Interface())
	if err != nil {
		return nil, err
	}

	s.Log.V(1).Info("received RPC response", "service", "yb.consensus.ConsensusService", "method", "RequestConsensusVote", "message", response)

	return response, nil
}

// Implements all of the one-by-one config change operations, including
// AddServer() and RemoveServer() from the Raft specification, as well as
// an operation to change the role of a server between VOTER and PRE_VOTER.
// An OK response means the operation was successful.

func (s *ConsensusServiceImpl) ChangeConfig(request *ChangeConfigRequestPB) (*ChangeConfigResponsePB, error) {
	s.Log.V(1).Info("sending RPC message", "service", "yb.consensus.ConsensusService", "method", "ChangeConfig", "message", request)
	response := &ChangeConfigResponsePB{}

	err := s.Messenger.SendMessage("yb.consensus.ConsensusService", "ChangeConfig", request.ProtoReflect().Interface(), response.ProtoReflect().Interface())
	if err != nil {
		return nil, err
	}

	s.Log.V(1).Info("received RPC response", "service", "yb.consensus.ConsensusService", "method", "ChangeConfig", "message", response)

	return response, nil
}

func (s *ConsensusServiceImpl) GetNodeInstance(request *GetNodeInstanceRequestPB) (*GetNodeInstanceResponsePB, error) {
	s.Log.V(1).Info("sending RPC message", "service", "yb.consensus.ConsensusService", "method", "GetNodeInstance", "message", request)
	response := &GetNodeInstanceResponsePB{}

	err := s.Messenger.SendMessage("yb.consensus.ConsensusService", "GetNodeInstance", request.ProtoReflect().Interface(), response.ProtoReflect().Interface())
	if err != nil {
		return nil, err
	}

	s.Log.V(1).Info("received RPC response", "service", "yb.consensus.ConsensusService", "method", "GetNodeInstance", "message", response)

	return response, nil
}

// Force this node to run a leader election.

func (s *ConsensusServiceImpl) RunLeaderElection(request *RunLeaderElectionRequestPB) (*RunLeaderElectionResponsePB, error) {
	s.Log.V(1).Info("sending RPC message", "service", "yb.consensus.ConsensusService", "method", "RunLeaderElection", "message", request)
	response := &RunLeaderElectionResponsePB{}

	err := s.Messenger.SendMessage("yb.consensus.ConsensusService", "RunLeaderElection", request.ProtoReflect().Interface(), response.ProtoReflect().Interface())
	if err != nil {
		return nil, err
	}

	s.Log.V(1).Info("received RPC response", "service", "yb.consensus.ConsensusService", "method", "RunLeaderElection", "message", response)

	return response, nil
}

// Notify originator about lost election, so it could reset its timeout.

func (s *ConsensusServiceImpl) LeaderElectionLost(request *LeaderElectionLostRequestPB) (*LeaderElectionLostResponsePB, error) {
	s.Log.V(1).Info("sending RPC message", "service", "yb.consensus.ConsensusService", "method", "LeaderElectionLost", "message", request)
	response := &LeaderElectionLostResponsePB{}

	err := s.Messenger.SendMessage("yb.consensus.ConsensusService", "LeaderElectionLost", request.ProtoReflect().Interface(), response.ProtoReflect().Interface())
	if err != nil {
		return nil, err
	}

	s.Log.V(1).Info("received RPC response", "service", "yb.consensus.ConsensusService", "method", "LeaderElectionLost", "message", response)

	return response, nil
}

// Force this node to step down as leader.

func (s *ConsensusServiceImpl) LeaderStepDown(request *LeaderStepDownRequestPB) (*LeaderStepDownResponsePB, error) {
	s.Log.V(1).Info("sending RPC message", "service", "yb.consensus.ConsensusService", "method", "LeaderStepDown", "message", request)
	response := &LeaderStepDownResponsePB{}

	err := s.Messenger.SendMessage("yb.consensus.ConsensusService", "LeaderStepDown", request.ProtoReflect().Interface(), response.ProtoReflect().Interface())
	if err != nil {
		return nil, err
	}

	s.Log.V(1).Info("received RPC response", "service", "yb.consensus.ConsensusService", "method", "LeaderStepDown", "message", response)

	return response, nil
}

// Get the latest committed or received opid on the server.

func (s *ConsensusServiceImpl) GetLastOpId(request *GetLastOpIdRequestPB) (*GetLastOpIdResponsePB, error) {
	s.Log.V(1).Info("sending RPC message", "service", "yb.consensus.ConsensusService", "method", "GetLastOpId", "message", request)
	response := &GetLastOpIdResponsePB{}

	err := s.Messenger.SendMessage("yb.consensus.ConsensusService", "GetLastOpId", request.ProtoReflect().Interface(), response.ProtoReflect().Interface())
	if err != nil {
		return nil, err
	}

	s.Log.V(1).Info("received RPC response", "service", "yb.consensus.ConsensusService", "method", "GetLastOpId", "message", response)

	return response, nil
}

// Returns the committed Consensus state.

func (s *ConsensusServiceImpl) GetConsensusState(request *GetConsensusStateRequestPB) (*GetConsensusStateResponsePB, error) {
	s.Log.V(1).Info("sending RPC message", "service", "yb.consensus.ConsensusService", "method", "GetConsensusState", "message", request)
	response := &GetConsensusStateResponsePB{}

	err := s.Messenger.SendMessage("yb.consensus.ConsensusService", "GetConsensusState", request.ProtoReflect().Interface(), response.ProtoReflect().Interface())
	if err != nil {
		return nil, err
	}

	s.Log.V(1).Info("received RPC response", "service", "yb.consensus.ConsensusService", "method", "GetConsensusState", "message", response)

	return response, nil
}

// Instruct this server to remotely bootstrap a tablet from another host.

func (s *ConsensusServiceImpl) StartRemoteBootstrap(request *StartRemoteBootstrapRequestPB) (*StartRemoteBootstrapResponsePB, error) {
	s.Log.V(1).Info("sending RPC message", "service", "yb.consensus.ConsensusService", "method", "StartRemoteBootstrap", "message", request)
	response := &StartRemoteBootstrapResponsePB{}

	err := s.Messenger.SendMessage("yb.consensus.ConsensusService", "StartRemoteBootstrap", request.ProtoReflect().Interface(), response.ProtoReflect().Interface())
	if err != nil {
		return nil, err
	}

	s.Log.V(1).Info("received RPC response", "service", "yb.consensus.ConsensusService", "method", "StartRemoteBootstrap", "message", response)

	return response, nil
}
