// Code generated by go-swagger; DO NOT EDIT.

package universe_information

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetMasterLeaderIPParams creates a new GetMasterLeaderIPParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMasterLeaderIPParams() *GetMasterLeaderIPParams {
	return &GetMasterLeaderIPParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetMasterLeaderIPParamsWithTimeout creates a new GetMasterLeaderIPParams object
// with the ability to set a timeout on a request.
func NewGetMasterLeaderIPParamsWithTimeout(timeout time.Duration) *GetMasterLeaderIPParams {
	return &GetMasterLeaderIPParams{
		timeout: timeout,
	}
}

// NewGetMasterLeaderIPParamsWithContext creates a new GetMasterLeaderIPParams object
// with the ability to set a context for a request.
func NewGetMasterLeaderIPParamsWithContext(ctx context.Context) *GetMasterLeaderIPParams {
	return &GetMasterLeaderIPParams{
		Context: ctx,
	}
}

// NewGetMasterLeaderIPParamsWithHTTPClient creates a new GetMasterLeaderIPParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMasterLeaderIPParamsWithHTTPClient(client *http.Client) *GetMasterLeaderIPParams {
	return &GetMasterLeaderIPParams{
		HTTPClient: client,
	}
}

/*
GetMasterLeaderIPParams contains all the parameters to send to the API endpoint

	for the get master leader IP operation.

	Typically these are written to a http.Request.
*/
type GetMasterLeaderIPParams struct {

	// CUUID.
	//
	// Format: uuid
	CUUID strfmt.UUID

	// UniUUID.
	//
	// Format: uuid
	UniUUID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get master leader IP params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMasterLeaderIPParams) WithDefaults() *GetMasterLeaderIPParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get master leader IP params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMasterLeaderIPParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get master leader IP params
func (o *GetMasterLeaderIPParams) WithTimeout(timeout time.Duration) *GetMasterLeaderIPParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get master leader IP params
func (o *GetMasterLeaderIPParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get master leader IP params
func (o *GetMasterLeaderIPParams) WithContext(ctx context.Context) *GetMasterLeaderIPParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get master leader IP params
func (o *GetMasterLeaderIPParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get master leader IP params
func (o *GetMasterLeaderIPParams) WithHTTPClient(client *http.Client) *GetMasterLeaderIPParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get master leader IP params
func (o *GetMasterLeaderIPParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCUUID adds the cUUID to the get master leader IP params
func (o *GetMasterLeaderIPParams) WithCUUID(cUUID strfmt.UUID) *GetMasterLeaderIPParams {
	o.SetCUUID(cUUID)
	return o
}

// SetCUUID adds the cUuid to the get master leader IP params
func (o *GetMasterLeaderIPParams) SetCUUID(cUUID strfmt.UUID) {
	o.CUUID = cUUID
}

// WithUniUUID adds the uniUUID to the get master leader IP params
func (o *GetMasterLeaderIPParams) WithUniUUID(uniUUID strfmt.UUID) *GetMasterLeaderIPParams {
	o.SetUniUUID(uniUUID)
	return o
}

// SetUniUUID adds the uniUuid to the get master leader IP params
func (o *GetMasterLeaderIPParams) SetUniUUID(uniUUID strfmt.UUID) {
	o.UniUUID = uniUUID
}

// WriteToRequest writes these params to a swagger request
func (o *GetMasterLeaderIPParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cUUID
	if err := r.SetPathParam("cUUID", o.CUUID.String()); err != nil {
		return err
	}

	// path param uniUUID
	if err := r.SetPathParam("uniUUID", o.UniUUID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
