// Code generated by go-swagger; DO NOT EDIT.

package schedule_external_script

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ExternalScriptScheduleReader is a Reader for the ExternalScriptSchedule structure.
type ExternalScriptScheduleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExternalScriptScheduleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewExternalScriptScheduleDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewExternalScriptScheduleDefault creates a ExternalScriptScheduleDefault with default headers values
func NewExternalScriptScheduleDefault(code int) *ExternalScriptScheduleDefault {
	return &ExternalScriptScheduleDefault{
		_statusCode: code,
	}
}

/* ExternalScriptScheduleDefault describes a response with status code -1, with default header values.

successful operation
*/
type ExternalScriptScheduleDefault struct {
	_statusCode int
}

// Code gets the status code for the external script schedule default response
func (o *ExternalScriptScheduleDefault) Code() int {
	return o._statusCode
}

func (o *ExternalScriptScheduleDefault) Error() string {
	return fmt.Sprintf("[POST /api/v1/customers/{cUUID}/universes/{uniUUID}/schedule_script][%d] externalScriptSchedule default ", o._statusCode)
}

func (o *ExternalScriptScheduleDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
