// Code generated by go-swagger; DO NOT EDIT.

package universe_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPauseUniverseParams creates a new PauseUniverseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPauseUniverseParams() *PauseUniverseParams {
	return &PauseUniverseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPauseUniverseParamsWithTimeout creates a new PauseUniverseParams object
// with the ability to set a timeout on a request.
func NewPauseUniverseParamsWithTimeout(timeout time.Duration) *PauseUniverseParams {
	return &PauseUniverseParams{
		timeout: timeout,
	}
}

// NewPauseUniverseParamsWithContext creates a new PauseUniverseParams object
// with the ability to set a context for a request.
func NewPauseUniverseParamsWithContext(ctx context.Context) *PauseUniverseParams {
	return &PauseUniverseParams{
		Context: ctx,
	}
}

// NewPauseUniverseParamsWithHTTPClient creates a new PauseUniverseParams object
// with the ability to set a custom HTTPClient for a request.
func NewPauseUniverseParamsWithHTTPClient(client *http.Client) *PauseUniverseParams {
	return &PauseUniverseParams{
		HTTPClient: client,
	}
}

/* PauseUniverseParams contains all the parameters to send to the API endpoint
   for the pause universe operation.

   Typically these are written to a http.Request.
*/
type PauseUniverseParams struct {

	// CUUID.
	//
	// Format: uuid
	CUUID strfmt.UUID

	// UniUUID.
	//
	// Format: uuid
	UniUUID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the pause universe params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PauseUniverseParams) WithDefaults() *PauseUniverseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the pause universe params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PauseUniverseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the pause universe params
func (o *PauseUniverseParams) WithTimeout(timeout time.Duration) *PauseUniverseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pause universe params
func (o *PauseUniverseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the pause universe params
func (o *PauseUniverseParams) WithContext(ctx context.Context) *PauseUniverseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pause universe params
func (o *PauseUniverseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the pause universe params
func (o *PauseUniverseParams) WithHTTPClient(client *http.Client) *PauseUniverseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pause universe params
func (o *PauseUniverseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCUUID adds the cUUID to the pause universe params
func (o *PauseUniverseParams) WithCUUID(cUUID strfmt.UUID) *PauseUniverseParams {
	o.SetCUUID(cUUID)
	return o
}

// SetCUUID adds the cUuid to the pause universe params
func (o *PauseUniverseParams) SetCUUID(cUUID strfmt.UUID) {
	o.CUUID = cUUID
}

// WithUniUUID adds the uniUUID to the pause universe params
func (o *PauseUniverseParams) WithUniUUID(uniUUID strfmt.UUID) *PauseUniverseParams {
	o.SetUniUUID(uniUUID)
	return o
}

// SetUniUUID adds the uniUuid to the pause universe params
func (o *PauseUniverseParams) SetUniUUID(uniUUID strfmt.UUID) {
	o.UniUUID = uniUUID
}

// WriteToRequest writes these params to a swagger request
func (o *PauseUniverseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cUUID
	if err := r.SetPathParam("cUUID", o.CUUID.String()); err != nil {
		return err
	}

	// path param uniUUID
	if err := r.SetPathParam("uniUUID", o.UniUUID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
