// Code generated by go-swagger; DO NOT EDIT.

package customer_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/yugabyte/yb-tools/yugaware-client/pkg/client/swagger/models"
)

// RetryTaskReader is a Reader for the RetryTask structure.
type RetryTaskReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RetryTaskReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRetryTaskOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRetryTaskOK creates a RetryTaskOK with default headers values
func NewRetryTaskOK() *RetryTaskOK {
	return &RetryTaskOK{}
}

/*
	RetryTaskOK describes a response with status code 200, with default header values.

successful operation
*/
type RetryTaskOK struct {
	Payload *models.UniverseResp
}

func (o *RetryTaskOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/customers/{cUUID}/tasks/{tUUID}/retry][%d] retryTaskOK  %+v", 200, o.Payload)
}
func (o *RetryTaskOK) GetPayload() *models.UniverseResp {
	return o.Payload
}

func (o *RetryTaskOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UniverseResp)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
