// Code generated by go-swagger; DO NOT EDIT.

package customer_configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/yugabyte/yb-tools/yugaware-client/pkg/client/swagger/models"
)

// DeleteCustomerConfigReader is a Reader for the DeleteCustomerConfig structure.
type DeleteCustomerConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteCustomerConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteCustomerConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteCustomerConfigOK creates a DeleteCustomerConfigOK with default headers values
func NewDeleteCustomerConfigOK() *DeleteCustomerConfigOK {
	return &DeleteCustomerConfigOK{}
}

/* DeleteCustomerConfigOK describes a response with status code 200, with default header values.

successful operation
*/
type DeleteCustomerConfigOK struct {
	Payload *models.YBPSuccess
}

func (o *DeleteCustomerConfigOK) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/customers/{cUUID}/configs/{configUUID}][%d] deleteCustomerConfigOK  %+v", 200, o.Payload)
}
func (o *DeleteCustomerConfigOK) GetPayload() *models.YBPSuccess {
	return o.Payload
}

func (o *DeleteCustomerConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.YBPSuccess)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
