// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
// The following only applies to changes made to this file as part of YugaByte development.
//
// Portions Copyright (c) YugaByte, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.  You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License
// is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
// or implied.  See the License for the specific language governing permissions and limitations
// under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.18.1
// source: yb/util/proto_container_test2.proto

package util

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Arbitrary protobuf that has one PB dependency.
type ProtoContainerTest2PB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Record *ProtoContainerTestPB `protobuf:"bytes,1,req,name=record" json:"record,omitempty"`
}

func (x *ProtoContainerTest2PB) Reset() {
	*x = ProtoContainerTest2PB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yb_util_proto_container_test2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoContainerTest2PB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoContainerTest2PB) ProtoMessage() {}

func (x *ProtoContainerTest2PB) ProtoReflect() protoreflect.Message {
	mi := &file_yb_util_proto_container_test2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoContainerTest2PB.ProtoReflect.Descriptor instead.
func (*ProtoContainerTest2PB) Descriptor() ([]byte, []int) {
	return file_yb_util_proto_container_test2_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoContainerTest2PB) GetRecord() *ProtoContainerTestPB {
	if x != nil {
		return x.Record
	}
	return nil
}

type TestObjectRequiredPB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	String1 *string               `protobuf:"bytes,1,req,name=string1" json:"string1,omitempty"`
	Record  *TestStringRequiredPB `protobuf:"bytes,2,req,name=record" json:"record,omitempty"`
	String2 *string               `protobuf:"bytes,3,req,name=string2" json:"string2,omitempty"`
}

func (x *TestObjectRequiredPB) Reset() {
	*x = TestObjectRequiredPB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yb_util_proto_container_test2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestObjectRequiredPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestObjectRequiredPB) ProtoMessage() {}

func (x *TestObjectRequiredPB) ProtoReflect() protoreflect.Message {
	mi := &file_yb_util_proto_container_test2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestObjectRequiredPB.ProtoReflect.Descriptor instead.
func (*TestObjectRequiredPB) Descriptor() ([]byte, []int) {
	return file_yb_util_proto_container_test2_proto_rawDescGZIP(), []int{1}
}

func (x *TestObjectRequiredPB) GetString1() string {
	if x != nil && x.String1 != nil {
		return *x.String1
	}
	return ""
}

func (x *TestObjectRequiredPB) GetRecord() *TestStringRequiredPB {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *TestObjectRequiredPB) GetString2() string {
	if x != nil && x.String2 != nil {
		return *x.String2
	}
	return ""
}

type TestObjectRepeatedPB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	String1 []string                `protobuf:"bytes,1,rep,name=string1" json:"string1,omitempty"`
	Record  []*TestStringRepeatedPB `protobuf:"bytes,2,rep,name=record" json:"record,omitempty"`
	String2 []string                `protobuf:"bytes,3,rep,name=string2" json:"string2,omitempty"`
}

func (x *TestObjectRepeatedPB) Reset() {
	*x = TestObjectRepeatedPB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yb_util_proto_container_test2_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestObjectRepeatedPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestObjectRepeatedPB) ProtoMessage() {}

func (x *TestObjectRepeatedPB) ProtoReflect() protoreflect.Message {
	mi := &file_yb_util_proto_container_test2_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestObjectRepeatedPB.ProtoReflect.Descriptor instead.
func (*TestObjectRepeatedPB) Descriptor() ([]byte, []int) {
	return file_yb_util_proto_container_test2_proto_rawDescGZIP(), []int{2}
}

func (x *TestObjectRepeatedPB) GetString1() []string {
	if x != nil {
		return x.String1
	}
	return nil
}

func (x *TestObjectRepeatedPB) GetRecord() []*TestStringRepeatedPB {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *TestObjectRepeatedPB) GetString2() []string {
	if x != nil {
		return x.String2
	}
	return nil
}

var File_yb_util_proto_container_test2_proto protoreflect.FileDescriptor

var file_yb_util_proto_container_test2_proto_rawDesc = []byte{
	0x0a, 0x23, 0x79, 0x62, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x32, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x79, 0x62, 0x1a, 0x22, 0x79, 0x62, 0x2f, 0x75, 0x74,
	0x69, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x49, 0x0a,
	0x15, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x54,
	0x65, 0x73, 0x74, 0x32, 0x50, 0x42, 0x12, 0x30, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x79, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x54, 0x65, 0x73, 0x74, 0x50, 0x42,
	0x52, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x22, 0x7c, 0x0a, 0x14, 0x54, 0x65, 0x73, 0x74,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x50, 0x42,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x31, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x31, 0x12, 0x30, 0x0a, 0x06, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x79, 0x62, 0x2e,
	0x54, 0x65, 0x73, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72,
	0x65, 0x64, 0x50, 0x42, 0x52, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x32, 0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x73,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x32, 0x22, 0x7c, 0x0a, 0x14, 0x54, 0x65, 0x73, 0x74, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x50, 0x42, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x31, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x07, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x31, 0x12, 0x30, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x79, 0x62, 0x2e, 0x54, 0x65,
	0x73, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x50, 0x42, 0x52, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x32, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x32,
}

var (
	file_yb_util_proto_container_test2_proto_rawDescOnce sync.Once
	file_yb_util_proto_container_test2_proto_rawDescData = file_yb_util_proto_container_test2_proto_rawDesc
)

func file_yb_util_proto_container_test2_proto_rawDescGZIP() []byte {
	file_yb_util_proto_container_test2_proto_rawDescOnce.Do(func() {
		file_yb_util_proto_container_test2_proto_rawDescData = protoimpl.X.CompressGZIP(file_yb_util_proto_container_test2_proto_rawDescData)
	})
	return file_yb_util_proto_container_test2_proto_rawDescData
}

var file_yb_util_proto_container_test2_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_yb_util_proto_container_test2_proto_goTypes = []interface{}{
	(*ProtoContainerTest2PB)(nil), // 0: yb.ProtoContainerTest2PB
	(*TestObjectRequiredPB)(nil),  // 1: yb.TestObjectRequiredPB
	(*TestObjectRepeatedPB)(nil),  // 2: yb.TestObjectRepeatedPB
	(*ProtoContainerTestPB)(nil),  // 3: yb.ProtoContainerTestPB
	(*TestStringRequiredPB)(nil),  // 4: yb.TestStringRequiredPB
	(*TestStringRepeatedPB)(nil),  // 5: yb.TestStringRepeatedPB
}
var file_yb_util_proto_container_test2_proto_depIdxs = []int32{
	3, // 0: yb.ProtoContainerTest2PB.record:type_name -> yb.ProtoContainerTestPB
	4, // 1: yb.TestObjectRequiredPB.record:type_name -> yb.TestStringRequiredPB
	5, // 2: yb.TestObjectRepeatedPB.record:type_name -> yb.TestStringRepeatedPB
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_yb_util_proto_container_test2_proto_init() }
func file_yb_util_proto_container_test2_proto_init() {
	if File_yb_util_proto_container_test2_proto != nil {
		return
	}
	file_yb_util_proto_container_test_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_yb_util_proto_container_test2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoContainerTest2PB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yb_util_proto_container_test2_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestObjectRequiredPB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yb_util_proto_container_test2_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestObjectRepeatedPB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_yb_util_proto_container_test2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yb_util_proto_container_test2_proto_goTypes,
		DependencyIndexes: file_yb_util_proto_container_test2_proto_depIdxs,
		MessageInfos:      file_yb_util_proto_container_test2_proto_msgTypes,
	}.Build()
	File_yb_util_proto_container_test2_proto = out.File
	file_yb_util_proto_container_test2_proto_rawDesc = nil
	file_yb_util_proto_container_test2_proto_goTypes = nil
	file_yb_util_proto_container_test2_proto_depIdxs = nil
}
