// Code generated by go-swagger; DO NOT EDIT.

package table_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/yugabyte/yb-tools/yugaware-client/pkg/client/swagger/models"
)

// NewCreateSingleTableBackupParams creates a new CreateSingleTableBackupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateSingleTableBackupParams() *CreateSingleTableBackupParams {
	return &CreateSingleTableBackupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateSingleTableBackupParamsWithTimeout creates a new CreateSingleTableBackupParams object
// with the ability to set a timeout on a request.
func NewCreateSingleTableBackupParamsWithTimeout(timeout time.Duration) *CreateSingleTableBackupParams {
	return &CreateSingleTableBackupParams{
		timeout: timeout,
	}
}

// NewCreateSingleTableBackupParamsWithContext creates a new CreateSingleTableBackupParams object
// with the ability to set a context for a request.
func NewCreateSingleTableBackupParamsWithContext(ctx context.Context) *CreateSingleTableBackupParams {
	return &CreateSingleTableBackupParams{
		Context: ctx,
	}
}

// NewCreateSingleTableBackupParamsWithHTTPClient creates a new CreateSingleTableBackupParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateSingleTableBackupParamsWithHTTPClient(client *http.Client) *CreateSingleTableBackupParams {
	return &CreateSingleTableBackupParams{
		HTTPClient: client,
	}
}

/*
CreateSingleTableBackupParams contains all the parameters to send to the API endpoint

	for the create single table backup operation.

	Typically these are written to a http.Request.
*/
type CreateSingleTableBackupParams struct {

	/* Backup.

	   Backup data to be created
	*/
	Backup *models.BackupTableParams

	// CUUID.
	//
	// Format: uuid
	CUUID strfmt.UUID

	// TableUUID.
	//
	// Format: uuid
	TableUUID strfmt.UUID

	// UniUUID.
	//
	// Format: uuid
	UniUUID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create single table backup params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateSingleTableBackupParams) WithDefaults() *CreateSingleTableBackupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create single table backup params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateSingleTableBackupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create single table backup params
func (o *CreateSingleTableBackupParams) WithTimeout(timeout time.Duration) *CreateSingleTableBackupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create single table backup params
func (o *CreateSingleTableBackupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create single table backup params
func (o *CreateSingleTableBackupParams) WithContext(ctx context.Context) *CreateSingleTableBackupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create single table backup params
func (o *CreateSingleTableBackupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create single table backup params
func (o *CreateSingleTableBackupParams) WithHTTPClient(client *http.Client) *CreateSingleTableBackupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create single table backup params
func (o *CreateSingleTableBackupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBackup adds the backup to the create single table backup params
func (o *CreateSingleTableBackupParams) WithBackup(backup *models.BackupTableParams) *CreateSingleTableBackupParams {
	o.SetBackup(backup)
	return o
}

// SetBackup adds the backup to the create single table backup params
func (o *CreateSingleTableBackupParams) SetBackup(backup *models.BackupTableParams) {
	o.Backup = backup
}

// WithCUUID adds the cUUID to the create single table backup params
func (o *CreateSingleTableBackupParams) WithCUUID(cUUID strfmt.UUID) *CreateSingleTableBackupParams {
	o.SetCUUID(cUUID)
	return o
}

// SetCUUID adds the cUuid to the create single table backup params
func (o *CreateSingleTableBackupParams) SetCUUID(cUUID strfmt.UUID) {
	o.CUUID = cUUID
}

// WithTableUUID adds the tableUUID to the create single table backup params
func (o *CreateSingleTableBackupParams) WithTableUUID(tableUUID strfmt.UUID) *CreateSingleTableBackupParams {
	o.SetTableUUID(tableUUID)
	return o
}

// SetTableUUID adds the tableUuid to the create single table backup params
func (o *CreateSingleTableBackupParams) SetTableUUID(tableUUID strfmt.UUID) {
	o.TableUUID = tableUUID
}

// WithUniUUID adds the uniUUID to the create single table backup params
func (o *CreateSingleTableBackupParams) WithUniUUID(uniUUID strfmt.UUID) *CreateSingleTableBackupParams {
	o.SetUniUUID(uniUUID)
	return o
}

// SetUniUUID adds the uniUuid to the create single table backup params
func (o *CreateSingleTableBackupParams) SetUniUUID(uniUUID strfmt.UUID) {
	o.UniUUID = uniUUID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateSingleTableBackupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Backup != nil {
		if err := r.SetBodyParam(o.Backup); err != nil {
			return err
		}
	}

	// path param cUUID
	if err := r.SetPathParam("cUUID", o.CUUID.String()); err != nil {
		return err
	}

	// path param tableUUID
	if err := r.SetPathParam("tableUUID", o.TableUUID.String()); err != nil {
		return err
	}

	// path param uniUUID
	if err := r.SetPathParam("uniUUID", o.UniUUID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
